name: Deploy
# https://github.com/marketplace/actions/deploy-to-heroku#deploy-with-docker

on:
  push:
    branches:
      - master
      - staging/*

jobs:
  build:
    runs-on: ubuntu-latest
    env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "nickjenkins" #Must be unique in Heroku
          heroku_email: "nickjenkins15051985@gmail.com"
          usedocker: true
